fix: Pegasus grab latest release from Github, refactored to better use  build cache

diff --git a/images/pegasus/Dockerfile b/images/pegasus/Dockerfile
--- a/images/pegasus/Dockerfile
+++ b/images/pegasus/Dockerfile
@@ -33,9 +33,6 @@ RUN \
 		rm -rf /var/lib/apt/lists/*
 
 # Install RetroArch
-# add-apt-repository ppa:libretro/stable && \
-#            libretro-core-info \
-#            libretro-frontend \
 RUN \
     echo "**** Install RetroArch ****" && \
         apt-get update && \
@@ -55,103 +52,70 @@ RUN \
 		apt-get autoremove -y && \
 		rm -rf /var/lib/apt/lists/*
 
-# Downloading PCSX2 AppImage
+# Install pegasus
+RUN  <<_INSTALL_PEGASUS
+  #!/bin/bash
+  set -e
+
+  echo "**** Installing pegasus ****"
+  apt-get update -y
+  apt-get install -y --no-install-recommends jq curl
+
+  # Pegasus still requires libssl1.1, but ubuntu switched to libssl3. Need to manually install it.
+  # TODO: Doing this could be a terrible idea (it does work)
+  wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb --output-document=libssl1.1.deb
+  apt-get install -y ./libssl1.1.deb
+
+  # Pegasus doesn't tag releases, they have a rolling weekly release
+  # so we have to parse the Github APIs to get the link
+  curl -s https://api.github.com/repos/mmatyas/pegasus-frontend/releases/tags/continuous | \
+  jq -r '.assets[] | select(.name | contains(".deb")) | .browser_download_url' | \
+  xargs curl -fsSL -o pegasus.deb
+
+  apt-get install -y ./pegasus.deb
+
+  # Cleanup
+  rm pegasus.deb libssl1.1.deb
+  apt-get remove -y jq curl
+  apt-get autoremove -y
+  rm -rf /var/lib/apt/lists/*
+_INSTALL_PEGASUS
+
 ARG PCS2_APP_IMAGE_URL=https://github.com/PCSX2/pcsx2/releases/download/v1.7.5232/pcsx2-v1.7.5232-linux-appimage-x64-Qt.AppImage
-RUN \
-    echo "**** Downloading PCSX2 AppImage ****" && \
-        mkdir -p /tmp && \
-        cd /tmp && \
-		wget -O pcsx2-emu-Qt.AppImage "${PCS2_APP_IMAGE_URL}"
-
-# Downloading XEMU AppImage
 ARG XEMU_APP_IMAGE_URL=https://github.com/xemu-project/xemu/releases/download/v0.7.117/xemu-v0.7.117-x86_64.AppImage
-RUN \
-    echo "**** Downloading XEMU AppImage ****" && \
-        mkdir -p /tmp && \
-        cd /tmp && \
-		wget -O xemu-emu.AppImage "${XEMU_APP_IMAGE_URL}"
-
-# Downloading RPCS3 AppImage
-# ARG RPCS3_APP_IMAGE_URL=https://github.com/RPCS3/rpcs3-binaries-linux/releases/download/build-98b764223285b2b1d474ece51027b936819adf46/rpcs3-v0.0.29-15813-98b76422_linux64.AppImage
 ARG RPCS3_APP_IMAGE_URL=https://github.com/RPCS3/rpcs3-binaries-linux/releases/download/build-9c354ee269779c5b473b39d313cbe1305040d138/rpcs3-v0.0.30-15970-9c354ee2_linux64.AppImage
-RUN \
-    echo "**** Downloading RPCS3 AppImage ****" && \
-        mkdir -p /tmp && \
-        cd /tmp && \
-        wget -O rpcs3-emu.AppImage "${RPCS3_APP_IMAGE_URL}"
-
-# Install Dolphin-emu
-# ARG DOLPHIN_APP_IMAGE_URL=https://github.com/project-slippi/Ishiiruka/releases/download/v3.3.1/Slippi_Online-x86_64.AppImage
-# ARG DOLPHIN_APP_IMAGE_URL=https://github.com/lucasmz1/Dolphin_emu_Appimage/releases/download/continuous-stable/Dolphin_Emulator-x86_64.AppImage
+ARG CEMU_APP_IMAGE_URL=https://github.com/cemu-project/Cemu/releases/download/v2.0-61/Cemu-2.0-61-x86_64.AppImage
 ARG DOLPHIN_APP_IMAGE_URL=https://github.com/qurious-pixel/dolphin/releases/download/continuous/Dolphin_Emulator-x86_64.AppImage
 # TODO: This is some randomly found AppImage. Need to find something more official
-RUN \
-    echo "**** Downloading Dolphin AppImage ****" && \
-        apt-get update && \
-        apt-get install -y \
-            qtbase5-dev \
-            qtbase5-dev-tools \
-            qt6-base-dev \
-            qt6-base-dev-tools && \
-        mkdir -p /tmp && \
-        cd /tmp && \
-        wget -O dolphin-emu.AppImage "${DOLPHIN_APP_IMAGE_URL}"
 
-# Install Cemu
-ARG CEMU_APP_IMAGE_URL=https://github.com/cemu-project/Cemu/releases/download/v2.0-61/Cemu-2.0-61-x86_64.AppImage
-RUN \
-    echo "**** Downloading CEMU AppImage ****" && \
-        mkdir -p /tmp && \
-        cd /tmp && \
-        wget -O cemu-emu.AppImage "${CEMU_APP_IMAGE_URL}"
+ARG APP_IMAGES_FOLDER=/Applications
+RUN <<_DOWNLOAD_APP_IMAGES
+  #!/bin/bash
+  set -e
 
-# Pegasus still requires libssl1.1, but ubuntu switched to libssl3. Need to manually install it.
-# TODO: Doing this could be a terrible idea (it does work)
-RUN wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb --output-document=libssl1.1.deb && \
-    dpkg -i libssl1.1.deb
+  echo "**** Downloading Emulators AppImages ****"
+  mkdir -p "${APP_IMAGES_FOLDER}"
 
-# Install pegasus
-ARG PEGASUS_DOWNLOAD=https://github.com/mmatyas/pegasus-frontend/releases/download/weekly_2023w20/pegasus-frontend_0.16.51_amd64.deb
-# ARG PEGASUS_DOWNLOAD=https://github.com/mmatyas/pegasus-frontend/releases/download/continuous/pegasus-frontend_0.16.77_amd64.deb
-RUN apt-get install -y --no-install-recommends \
-    fontconfig \
-    gstreamer1.0-alsa \
-    gstreamer1.0-libav \
-    gstreamer1.0-plugins-good \
-    gstreamer1.0-gl \
-    libgstreamer1.0-dev \
-    libsdl2-2.0-0 \
-    libxcb-glx0 \
-    libxcb-icccm4 \
-    libxcb-image0 \
-    libxcb-keysyms1 \
-    libxcb-randr0 \
-    libxcb-render-util0 \
-    libxcb-shape0 \
-    libxcb-shm0 \
-    libxcb-sync1 \
-    libxcb-xfixes0 \
-    libxcb-xinerama0 \
-    libxcb-xkb1 \
-    libxkbcommon-x11-0 \
-    libzstd1 \
-    policykit-1 \
-    unzip && \
-    wget $PEGASUS_DOWNLOAD --output-document=pegasus-frontend.deb && \
-    dpkg -i pegasus-frontend.deb
+  wget -O "${APP_IMAGES_FOLDER}"/pcsx2-emu-Qt.AppImage "${PCS2_APP_IMAGE_URL}"
+  wget -O "${APP_IMAGES_FOLDER}"/xemu-emu.AppImage "${XEMU_APP_IMAGE_URL}"
+  wget -O "${APP_IMAGES_FOLDER}"/cemu-emu.AppImage "${CEMU_APP_IMAGE_URL}"
+  wget -O "${APP_IMAGES_FOLDER}"/dolphin-emu.AppImage "${DOLPHIN_APP_IMAGE_URL}"
 
-# Move all the apps out of /tmp and to the /Applications folder
-RUN \
-    echo "**** Preparing Applications for symlinking ****" && \
-        mkdir -p /Applications && \
-        mv /tmp/*.AppImage /Applications && \
-		chmod -v -R 777 /Applications/ && \
-		chmod -v -R a+x /Applications/
+  # Dolphin extra deps
+  apt-get update -y
+  apt-get install -y \
+  qtbase5-dev \
+  qtbase5-dev-tools \
+  qt6-base-dev \
+  qt6-base-dev-tools
 
-# Cleanup
-RUN apt-get remove -y software-properties-common gpg-agent && \
-    apt-get autoremove -y && \
-    rm -rf /var/lib/apt/lists/*
+  chmod -v -R 777 /Applications/
+  chmod -v -R a+x /Applications/
+
+  # Cleanup
+  apt-get autoremove -y
+  rm -rf /var/lib/apt/lists/*
+_DOWNLOAD_APP_IMAGES
 
 # Copy config files
 COPY --chmod=777 scripts/startup.sh /opt/gow/startup-app.sh
